# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddingWorker.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addingWorker(object):
    def setupUi(self, addingWorker):
        addingWorker.setObjectName("addingWorker")
        addingWorker.resize(323, 364)
        addingWorker.setStyleSheet("background-color: #3a3a47;")
        self.centralwidget = QtWidgets.QWidget(addingWorker)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(24, 156, 289, 37))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.hl_id = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.hl_id.setContentsMargins(0, 0, 0, 0)
        self.hl_id.setObjectName("hl_id")
        self.lbl_id = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_id.setFont(font)
        self.lbl_id.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_id.setObjectName("lbl_id")
        self.hl_id.addWidget(self.lbl_id)
        self.le_id = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.le_id.setFont(font)
        self.le_id.setStyleSheet("color: rgb(255, 255, 255);")
        self.le_id.setObjectName("le_id")
        self.hl_id.addWidget(self.le_id)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(24, 78, 289, 73))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vl_name = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vl_name.setContentsMargins(0, 0, 0, 0)
        self.vl_name.setObjectName("vl_name")
        self.hl_Fname = QtWidgets.QHBoxLayout()
        self.hl_Fname.setObjectName("hl_Fname")
        self.lbl_Fname = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Fname.setFont(font)
        self.lbl_Fname.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_Fname.setObjectName("lbl_Fname")
        self.hl_Fname.addWidget(self.lbl_Fname)
        self.le_Fname = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.le_Fname.setFont(font)
        self.le_Fname.setStyleSheet("color: rgb(255, 255, 255);")
        self.le_Fname.setObjectName("le_Fname")
        self.hl_Fname.addWidget(self.le_Fname)
        self.vl_name.addLayout(self.hl_Fname)
        self.hl_Sname = QtWidgets.QHBoxLayout()
        self.hl_Sname.setObjectName("hl_Sname")
        self.lbl_Sname = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Sname.setFont(font)
        self.lbl_Sname.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_Sname.setObjectName("lbl_Sname")
        self.hl_Sname.addWidget(self.lbl_Sname)
        self.le_Sname = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.le_Sname.setFont(font)
        self.le_Sname.setStyleSheet("color: rgb(255, 255, 255);")
        self.le_Sname.setObjectName("le_Sname")
        self.hl_Sname.addWidget(self.le_Sname)
        self.vl_name.addLayout(self.hl_Sname)
        self.lbl_title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_title.setGeometry(QtCore.QRect(60, 30, 217, 37))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_title.sizePolicy().hasHeightForWidth())
        self.lbl_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setWhatsThis("")
        self.lbl_title.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(558, 666, 163, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_add.setFont(font)
        self.btn_add.setStyleSheet("QPushButton{\n"
"  background-color: rgb(255, 171, 2);\n"
"  border: none;\n"
"  color: white;\n"
"  text-decoration: none;\n"
"  display: inline-block;\n"
"  cursor: pointer;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 137, 2);\n"
"    color: rgb(217, 217, 217);\n"
"}")
        self.btn_add.setAutoDefault(False)
        self.btn_add.setDefault(False)
        self.btn_add.setFlat(False)
        self.btn_add.setObjectName("btn_add")
        self.cb_type = QtWidgets.QComboBox(self.centralwidget)
        self.cb_type.setGeometry(QtCore.QRect(72, 246, 199, 31))
        self.cb_type.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cb_type.setFont(font)
        self.cb_type.setStyleSheet("color: #FFF;")
        self.cb_type.setObjectName("cb_type")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(24, 198, 289, 37))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.hl_id_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.hl_id_2.setContentsMargins(0, 0, 0, 0)
        self.hl_id_2.setObjectName("hl_id_2")
        self.lbl_id_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_id_2.setFont(font)
        self.lbl_id_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_id_2.setObjectName("lbl_id_2")
        self.hl_id_2.addWidget(self.lbl_id_2)
        self.le_id_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.le_id_2.setFont(font)
        self.le_id_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.le_id_2.setObjectName("le_id_2")
        self.hl_id_2.addWidget(self.le_id_2)
        self.lbl_add = QtWidgets.QPushButton(self.centralwidget)
        self.lbl_add.setGeometry(QtCore.QRect(78, 294, 175, 28))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lbl_add.setFont(font)
        self.lbl_add.setStyleSheet("QPushButton{\n"
"  background-color: rgb(255, 171, 2);\n"
"  border: none;\n"
"  color: white;\n"
"  text-decoration: none;\n"
"  display: inline-block;\n"
"  cursor: pointer;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 137, 2);\n"
"    color: rgb(217, 217, 217);\n"
"}")
        self.lbl_add.setObjectName("lbl_add")
        addingWorker.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(addingWorker)
        self.statusbar.setObjectName("statusbar")
        addingWorker.setStatusBar(self.statusbar)

        self.retranslateUi(addingWorker)
        QtCore.QMetaObject.connectSlotsByName(addingWorker)

    def retranslateUi(self, addingWorker):
        _translate = QtCore.QCoreApplication.translate
        addingWorker.setWindowTitle(_translate("addingWorker", "Adding worker"))
        self.lbl_id.setText(_translate("addingWorker", "Id:"))
        self.lbl_Fname.setText(_translate("addingWorker", "First name:"))
        self.lbl_Sname.setText(_translate("addingWorker", "Second name:"))
        self.lbl_title.setText(_translate("addingWorker", "Adding worker"))
        self.btn_add.setText(_translate("addingWorker", "add/change"))
        self.cb_type.setItemText(0, _translate("addingWorker", "Choose type"))
        self.cb_type.setItemText(1, _translate("addingWorker", "Manager"))
        self.cb_type.setItemText(2, _translate("addingWorker", "Programmer"))
        self.cb_type.setItemText(3, _translate("addingWorker", "Designer"))
        self.lbl_id_2.setText(_translate("addingWorker", "Password:"))
        self.lbl_add.setText(_translate("addingWorker", "Add"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addingWorker = QtWidgets.QMainWindow()
    ui = Ui_addingWorker()
    ui.setupUi(addingWorker)
    addingWorker.show()
    sys.exit(app.exec_())
